deployment:
  tasks:
    - rsync -av --delete \
      --exclude='public' \
      --exclude='.env' \
      --exclude='storage' \
      --exclude='node_modules' \
      /home/akkpwaka/repositories/profil.akkpwakatobi.ac.id/ \
      /home/akkpwaka/profil.akkpwakatobi.ac.id/

      - rsync -av --exclude='uploads' public/ /home/akkpwaka/public_html/profil/

    - rsync -av --delete \
      --exclude='index.php' \
      /home/akkpwaka/repositories/profil.akkpwakatobi.ac.id/public/ \
      /home/akkpwaka/public_html/profil/

    - cd /home/akkpwaka/profil.akkpwakatobi.ac.id
    - php artisan optimize:clear
